jobs:
  check-license:
    name: Check license header
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Check license header
      uses: apache/skywalking-eyes@v0.3.0
      with:
        config: .licenserc.yaml
        log: info
name: InLong Check License Header
on:
  repository_dispatch:
    types: trigger-ga___ci_check_license.yml
