env:
  CT_CONFIG_PATH: .github/ct.yml
  KIND_CONFIG_PATH: .github/kind.yml
jobs:
  chart-test:
    name: Lint and test charts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - continue-on-error: true
      name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.5.0
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - continue-on-error: true
      name: Set up chart-testing
      uses: ./.github/actions/chart-testing-action
    - continue-on-error: true
      id: list-changed
      name: List changed charts
      run: "changed=$(ct list-changed --config ${{ env.CT_CONFIG_PATH }} --target-branch\
        \ ${{ github.event.repository.default_branch }})\nif [[ -n \"$changed\" ]];\
        \ then\n  echo \"changed=true\" >> $GITHUB_OUTPUT\n  echo \"Changed charts:\
        \ $changed\"\nelse\n  echo \"Charts are not changed, they will not be linted,\
        \ validated, installed and tested.\"\nfi\n"
    - continue-on-error: true
      name: Lint and validate charts
      run: ct lint --config ${{ env.CT_CONFIG_PATH }}
    - continue-on-error: true
      if: ${{ steps.list-changed.outputs.changed == 'true' }}
      name: Create Kind cluster
      uses: ./.github/actions/kind-action
      with:
        config: ${{ env.KIND_CONFIG_PATH }}
        node_image: ${{ matrix.kubernetes-version }}
    - continue-on-error: true
      if: ${{ success() && steps.list-changed.outputs.changed == 'true' }}
      name: Install and test charts
      run: ct install --config ${{ env.CT_CONFIG_PATH }}
    strategy:
      matrix:
        kubernetes-version:
        - kindest/node:v1.21.10
        - kindest/node:v1.23.4
name: InLong Helm Charts Lint and Test
on:
  repository_dispatch:
    types: trigger-ga___ci_chart_test.yml
