jobs:
  check:
    name: Check pull request title
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      if: ${{ github.event_name == 'pull_request_target' }}
      name: Check title
      run: "if [[ ! \"$PR_TITLE\" =~ ^\\[(WIP|INLONG-[0-9]+)\\]\\[[a-zA-Z]+\\].*$\
        \ ]]; then\n  echo \"This pull request title is not valid.\"\n  echo \"Title\
        \ Example: [INLONG-XYZ][Component] Title of the pull request\"\n  echo \"\
        XYZ should be replaced by the actual GitHub Issue number, e.g. [INLONG-123]\"\
        \n  echo \"Component should be replaced by the InLong component name, e.g.\
        \ [INLONG-123][Manager]\"\n\n  # add a job summary\n  echo \"## This pull\
        \ request title is not valid! :bug:\" >> $GITHUB_STEP_SUMMARY\n  echo \"Title\
        \ Example: \\`[INLONG-XYZ][Component] Title of the pull request\\`\" >> $GITHUB_STEP_SUMMARY\n\
        \  echo \"> - **XYZ** should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues)\
        \ number, e.g. \\`[INLONG-123]\\`\" >> $GITHUB_STEP_SUMMARY\n  echo \"> -\
        \ **Component** should be replaced by the InLong component name, e.g. \\`[INLONG-123][Manager]\\\
        `\" >> $GITHUB_STEP_SUMMARY\n\n  exit 1\nfi\n"
name: InLong Check Pull Request Title
on:
  repository_dispatch:
    types: trigger-ga___ci_check_pr_title.yml
