jobs:
  greeting:
    name: Greeting
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Interact with newcomers
      uses: actions/first-interaction@v1
      with:
        issue-message: "Hello @${{ github.actor }}, thank you for opening your first\
          \ issue in InLong \U0001F9E1 We will respond as soon as possible \u23F3\n\
          If this is a bug report, please provide screenshots or error logs for us\
          \ to reproduce your issue, so we can do our best to fix it.\nIf you have\
          \ any questions in the meantime, you can also ask us on the [InLong Discussions](https://github.com/apache/inlong/discussions)\
          \ \U0001F50D\n"
        pr-message: "Hello @${{ github.actor }}, thank you for submitting a PR to\
          \ InLong \U0001F496 We will respond as soon as possible \u23F3\nThis seems\
          \ to be your first PR \U0001F320 Please be sure to follow our [Contribution\
          \ Guidelines](https://inlong.apache.org/community/how-to-contribute).\n\
          If you have any questions in the meantime, you can also ask us on the [InLong\
          \ Discussions](https://github.com/apache/inlong/discussions) \U0001F50D\n"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: InLong Greeting
on:
  repository_dispatch:
    types: trigger-ga___ci_greeting.yml
