jobs:
  label:
    name: Label
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Label the PR
      uses: actions/labeler@v4
      with:
        configuration-path: .github/labeler.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true
name: InLong Pull Request Labeler
on:
  repository_dispatch:
    types: trigger-ga___ci_labeler.yml
