jobs:
  stale:
    name: Stale
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Mark issues and PRs
      uses: actions/stale@v5
      with:
        days-before-issue-close: -1
        days-before-issue-stale: 60
        days-before-pr-close: -1
        days-before-pr-stale: 60
        exempt-issue-labels: WIP
        exempt-pr-labels: WIP
        operations-per-run: 500
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: stage/stale
        stale-issue-message: This issue is stale because it has been open for 60 days
          with no activity.
        stale-pr-label: stage/stale
        stale-pr-message: This PR is stale because it has been open for 60 days with
          no activity.
name: InLong Mark Stale Issues and PRs
on:
  repository_dispatch:
    types: trigger-ga___ci_stale.yml
