jobs:
  unit-test:
    name: Unit Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 8
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-inlong-flink15-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/inlong

          '
        restore-keys: ${{ runner.os }}-inlong-flink15
    - continue-on-error: true
      env:
        CI: false
      name: Build for Flink 1.15 with Maven
      run: mvn --update-snapshots -e -V clean install -U -pl :sort-core,:sort-end-to-end-tests-v1.15
        -am -Pv1.15 -DskipTests -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
        -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Daether.connector.http.reuseConnections=false
        -Daether.connector.requestTimeout=60000
    - continue-on-error: true
      env:
        CI: false
      name: Unit test for Flink 1.15 with Maven
      run: mvn --update-snapshots -e -V verify -pl :sort-core,:sort-end-to-end-tests-v1.15
        -am -Pv1.15
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload unit test results
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: surefire-reports
        path: ./**/target/surefire-reports/
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload integration test results
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: failsafe-reports
        path: ./**/target/failsafe-reports/
    - continue-on-error: true
      name: Clean up build packages
      run: mvn clean
name: InLong Unit Test For Flink 1.15
on:
  repository_dispatch:
    types: trigger-ga___ci_ut_flink15.yml
